name: Continues Evaluation Browser Use

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      pipeline_id:
        description: 'Pipeline ID'
        required: true
        default: '75'
      user_id:
        description: 'User ID'
        required: false
        default: 'cme2gz7zn000005os2yuj36h8'
      model:
        description: 'Model'
        required: true
        type: choice
        options:
          - gpt-4o
          - gemini-2.5-pro-preview-06-05
          - claude-sonnet-4-20250514
        default: 'gemini-2.5-pro-preview-06-05'
      advanced_settings:
        description: 'Advanced Settings (JSON)'
        required: false
        default: '{"use_vision":true,"temperature":0,"max_steps":10,"max_actions_per_step":50,"max_failures":3,"retry_delay":10,"generate_gif":false,"episodes":2}'
      episodes:
        description: 'Number of episodes to run'
        required: true
        type: number
        default: 2

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: short-sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Prepare advanced settings
        id: settings
        run: | 
          SETTINGS='${{ inputs.advanced_settings }}'
          ENCODED=$(echo "$SETTINGS" | base64 -w 0)
          echo "advanced_settings_b64=$ENCODED" >> $GITHUB_OUTPUT
        
      - name: Send payload to Paradigm Shift
        run: |
          cat > payload.json <<'JSON'
          {
            "agent_name": "browser-use",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "commit_sha": "${{ steps.short-sha.outputs.short_sha }}",
            "pipeline_id": "${{ inputs.pipeline_id || '75' }}",
            "user_id": "${{ inputs.user_id || 'cme2gz7zn000005os2yuj36h8' }}",
            "model": "${{ inputs.model || 'gemini-2.5-pro-preview-06-05' }}",
            "advanced_settings": "${{ steps.settings.outputs.advanced_settings_b64 }}",
            "episodes": ${{ inputs.episodes || 1 }}
          }
          JSON
          curl -fsS -H "Content-Type: application/json" -d @payload.json https://smee.io/7mZr6jobxcc3WeLj


